### PR TITLE
DRAFT free rawInput buffer when empty and copy down remaining data instead …

### PR DESCRIPTION
**Pull request by acgreek**
…of using an offset

### CODE REVIEW

**Comment by lesismal** [comment]
The offset can not be removed, because of half-packet/sticky-packet.

**Comment by acgreek** [comment]
Did you notice the copy I used instead of of the one place where
rawInputOff is set? Why won't that work?

**Comment by acgreek** [comment]
```
	// Process message.
-	record := c.rawInput[c.rawInputOff : c.rawInputOff+recordHeaderLen+n]
-	c.rawInputOff += (recordHeaderLen + n)
-	if len(c.rawInput) == c.rawInputOff {
-		c.rawInput = c.rawInput[0:0]
-		c.rawInputOff = 0
+	record := c.rawInput[:recordHeaderLen+n]
+	rawInputOffset := (recordHeaderLen + n)
+	remaining := len(c.rawInput) - rawInputOffset

+	if remaining == 0 {
+		c.allocator.Free(c.rawInput)
+		c.rawInput = nil
+	} else {
+		copy(c.rawInput, c.rawInput[rawInputOffset:])
+		c.rawInput = c.rawInput[:remaining]
```

**Comment by lesismal** [comment]
maybe we could add a new method: tls.Conn.ResetOrFreeBuffer
```golang
func (c *Conn) ResetOrFreeBuffer() {
	c.closeMux.Lock()
	defer c.closeMux.Unlock()
	if c.closed {
		return
	}

	remain := len(c.rawInput) - c.rawInputOff
	switch remain {
	case 0:
		if c.rawInput != nil {
			c.allocator.Free(c.rawInput)
			c.rawInput = nil
		}
	default:
		copy(c.rawInput, c.rawInput[c.rawInputOff:])
		c.rawInput = c.rawInput[:remain]
	}
}
```

and call it in a defer func here:
https://github.com/lesismal/nbio/blob/master/nbhttp/engine.go#L313
```golang
// TLSDataHandler .
func (e *Engine) TLSDataHandler(c *nbio.Conn, data []byte) {
	defer func() {
		if err := recover(); err != nil {
			const size = 64 << 10
			buf := make([]byte, size)
			buf = buf[:runtime.Stack(buf, false)]
			logging.Error("execute parser failed: %v\n%v\n", err, *(*string)(unsafe.Pointer(&buf)))
		}
	}()

	parser := c.Session().(*Parser)
	if parser == nil {
		logging.Error("nil parser")
		c.Close()
		return
	}
	if tlsConn, ok := parser.Processor.Conn().(*tls.Conn); ok {
		defer func() {
			tlsConn.ResetOrFreeBuffer()
		}()
		buffer := e.getTLSBuffer(c)
		for {
			_, nread, err := tlsConn.AppendAndRead(data, buffer)
			data = nil
			if err != nil {
				c.CloseWithError(err)
				return
			}
			if nread > 0 {
				err := parser.Read(buffer[:nread])
				if err != nil {
					logging.Debug("parser.Read failed: %v", err)
					c.CloseWithError(err)
					return
				}
			}
			if nread == 0 {
				return
			}
		}
	}
}
```

Then we avoid copy data every time when there are multi frames.
But check after the full reading from the application layer: if there's data left, we move the last half frame ahead, else free the `rawInput` if no data left.

**Pull request closed without merging**
